### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Nenek Trivia
email: terryrockstar22@gmail.com
description: ¡Hola! en Tenek
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nenek-trivia.web.app/" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
twitter_username: Terry_rockstar
github_username:  terry0022
author: Enrique Espinoza
logo: assets/images/large-logo.png
twitter:
  username: Terry_rockstar
social:
  name: Enrique Espinoza
  links:
    - https://twitter.com/Terry_rockstar
    - https://fb.com/terryrockstar
    - https://www.linkedin.com/in/enrique0022/
    - https://github.com/terry0022

languages: ["es"]
ampdir: amp

github: https://github.com/terry0022/nenek-trivia-landing

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
