name: Nenek Trivia
description: ¿Cuánto conoces de la Huasteca Potosina? ¡Ven y descúbrelo en esta nueva App!
full_description: '<p>La huasteca potosina es una de las cuatro regiones mas ricas en cuanto a biodiversidad, cultura y tradiciones del estado de San Luis Potosí.</p>
<p>Nenek Trivia es una aplicación en la cual pondrás a prueba tus conocimientos sobre esta hermosa región con diferentes preguntas, a través de las cuales descubrirás su geografía, sus tradiciones, su gastronomía y parte de la historia de sus municipios, forma parte de Nenek Trivia y contesta las preguntas antes de que termine el tiempo, junta todos los puntos que puedas para estar en la lista de mejores jugadores.</p>
<p>Invita a tus amigos a participar y competir para saber quien tiene mayor conocimiento acerca de la Huasteca Potosina.</p>'
android: https://play.google.com/store/apps/details?id=com.fenixarts.nenektrivia
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png